### ISSUE TITLE
Video interplay and flickering

### ISSUE THREAD

**Issue by SatanNintendo** [Luna-Project64/Luna-Project64#104]
In some games, there is an interlace, not a very pleasant picture, but there is an interlace in the original ParaLLEl RDP, but in the Luna version there is also a flicker at some points.
If this can be fixed, it would be really great.

The problem with the interface was discussed in this topic: https://github.com/ata4/angrylion-rdp-plus/issues/161

Well, there is no flicker in the original ParaLLEl RDP, this was not discussed.
If you need examples of flickering, I can record a short video next time.

**Comment by SatanNintendo** [comment]
It seems that this doesn't work well with the "Wave" deinterlaser, and everything is fine with the "Bob" deinterlaser, but "Bob" itself is not very good, everything is twitching, especially the text.

**Comment by SatanNintendo** [comment]
I decided to record a short video of how the flickering occurs.
I use ParaLLEl both RSP and RDP plugins.

https://github.com/user-attachments/assets/bd18f2ea-8782-49e8-b3a4-abc015c8ac5d

This happens in different games and it's not always possible to capture the moment, but on Windows 11 it works better, as in the video, and on Windows 7 the flickering is more frequent.

My system:
NVIDIA RTX 2060 Super (8GB)
16GB RAM (DDR3)
CPU: i7 2600K 4 Cores 8 Threads

I did video recording in Windows 11, where it's rare to catch it.

![Image](https://github.com/user-attachments/assets/fd3e4d8b-9980-4075-8280-569048954bfb)

Well, the interlace itself is also present, but this is the second problem, it is also in the original, but there is no flicker in the original in my case, I'm talking about the original ParaLLEl RDP.

You can also notice how at some point the game starts to slow down, perhaps this is due to my system, but at other times, if you turn off the fps limit, the game runs 300%+

**Comment by aglab2** [comment]
I have fixed some race conditions in the code (related to https://github.com/Luna-Project64/Luna-Project64/issues/110#issuecomment-3678950540) , maybe it will help 

[Project64.zip](https://github.com/user-attachments/files/24354001/Project64.zip)

Also what game is this?

**Comment by SatanNintendo** [comment]
> I have fixed some race conditions in the code (related to [#110 (comment)](https://github.com/Luna-Project64/Luna-Project64/issues/110#issuecomment-3678950540)) , maybe it will help
> 
> [Project64.zip](https://github.com/user-attachments/files/24354001/Project64.zip)
> 
> Also what game is this?

Hi! It's hard to say for sure, this doesn't always happen, but according to my tests today, at first glance everything seems to be working well.

There are only interlacing strips left, but this is also present in the original ParaLLEl RDP.

The game that I have in my example is "Killer Instinct Gold".

By the way, I didn't notice right away, there's a wrong display of the scale itself on the health scale of the characters.

![Image](https://github.com/user-attachments/assets/78729cfc-d777-44c2-8784-6811fc773d84)

**Comment by aglab2** [comment]
Hi, please try this version of [Project64.zip](https://github.com/user-attachments/files/24359944/Project64.zip), it should be fix the issues with the health bar.

I am still not sure what exactly is happening with Bob deinterlacing (why is it jittering). Weave deinterlacer is apparently meant to have interlaced artifacts and I recommend not using it.

**Comment by SatanNintendo** [comment]
> Hi, please try this version of [Project64.zip](https://github.com/user-attachments/files/24359944/Project64.zip), it should be fix the issues with the health bar.
> 
> I am still not sure what exactly is happening with Bob deinterlacing (why is it jittering). Weave deinterlacer is apparently meant to have interlaced artifacts and I recommend not using it.

Hi! Everything is fine, now there are no problems with displaying the health scale.
As for interlacing, apparently this is normal for "wave", it's just that in this game this interlacing is not visible everywhere, well, at least there are no graphical bugs and flickering now, thanks a lot for the fixes.

May I ask in this post?
There is a filtering mode in the "AngryLion RDP" video plugin, and "ParaLLEl RDP" is based on "AngryLion", but in "ParaLLEl" I can't make the filtering mode so that the picture is close to what "AngryLion" gives out, if you look closely, then sharp ladders remain in the games, in "AngryLion" looks like bilinear interpolation, which smooths it out.
Is there no way to set a filter in "ParaLLEl" that could bring the image closer to "AngryLion"?

As for Killer Instinct Gold, according to today's tests, it looks like the problem has been solved, thanks again.

**Comment by aglab2** [comment]
Let's create a separate feature request issue regarding bilinear filtering from Angrylion and keep this one only about flickering/interplay.

**Comment by aglab2** [comment]
I believe I managed to fix jittering with Bob deinterlacer enabled in Star Wars/Killer Instinct Gold. There is still some artifacts on the very edge of the screen, likely need to use overscan to clip those or just ignore. The picture itself seems to be stable.

[Project64.zip](https://github.com/user-attachments/files/24360482/Project64.zip)

**Comment by SatanNintendo** [comment]
> I believe I managed to fix jittering with Bob deinterlacer enabled in Star Wars/Killer Instinct Gold. There is still some artifacts on the very edge of the screen, likely need to use overscan to clip those or just ignore. The picture itself seems to be stable.
> 
> [Project64.zip](https://github.com/user-attachments/files/24360482/Project64.zip)

Wow, I didn't even notice, I always played in "wave" mode because I didn't like the shaking in "bob" mode, but now I switched to "bob" and everything looks good, it definitely looks nicer.

I want to make a reservation right away that the "bob" mode was fixed, but at the same time, in the "wave" mode, the image completely broke in this build.

https://github.com/user-attachments/assets/c251c026-8622-4d74-bcb4-a29d9d02e0d3

**Comment by SatanNintendo** [comment]
By the way, in the "bob" mode, the filtering has become better, closer to "AngryLion" in my opinion.
Now you can use "bob", if you have to sacrifice the "wave" mode, then it's probably worth it.

**Comment by aglab2** [comment]
I "fixed" Weave mode, I did not properly handle the conditions for final pass. It is still not worth using though compared to patched Bob.

[Project64.zip](https://github.com/user-attachments/files/24365052/Project64.zip)

I assume this task is complete and can be closed.

**Comment by SatanNintendo** [comment]
> I "fixed" Weave mode, I did not properly handle the conditions for final pass. It is still not worth using though compared to patched Bob.
> 
> [Project64.zip](https://github.com/user-attachments/files/24365052/Project64.zip)
> 
> I assume this task is complete and can be closed.

Hi! Sorry for the long answer, I just got home.
I confirm that it looks fine in all variants now.
Thanks a lot for these fixes. they are especially pleasant for me, as I use these plugins to be closer to the real console.
Happy New Year soon! ;)
